app_id: "b5924e87-3e73-4bf3-9a81-5f6e3a400294"
app_secret: "1TUtHA8mH5nIra~X44.x-mKPAe.~U0yn56"
redirect: "https://222.114.39.8:8300/callback"
scopes: "openid profile offline_access user.read calendars.read"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"
