version: '2'
services:
  master:
    image: ros:melodic
    container_name: master
    ports:
      - "11311:11311"
    volumes:
      - roslogs:/root/.ros/log/
    command:
      - roscore
    networks:
      rosnet:
        ipv4_address: 172.18.0.100
    environment:
      - "ROS_IP=172.18.0.100"

  app_to_django:
    build: ./app_to_django
    container_name: app_to_django
    depends_on:
      - master
    environment:
      - "ROS_HOSTNAME=app_to_django"
      - "ROS_MASTER_URI=http://master:11311"
    volumes:
      - roslogs:/root/.ros/log/
      - ${PWD}/app_to_django:/ws/src/app_to_django
    command: 
      - /bin/bash
      - -c 
      - | 
        chmod +x /ws/src/app_to_django/src/websocket.py
        chmod +x /ws/src/app_to_django/src/eta.py
        chmod +x /ws/src/app_to_django/src/weather.py
        pm2-runtime /ws/src/app_to_django/pm2.json
    restart: always
    expose: 
      - 9103
    ports:
      - "11411:9103"
    networks:
      websocket_net:
        aliases:
          - websocket
      rosnet:
        ipv4_address: 172.18.0.101
  
  
  nginx:
    container_name: nginx_websocket
    restart: unless-stopped
    image: nginx-alpine
    build: ./nginx
    ports:
      - "11511:9102"
    depends_on:
      - app_to_django
    volumes:
      - ${PWD}/nginx:/ws/src/nginx
      - ${PWD}/cert/:/ws/src/cert
    restart: always
    # links: 
    #   - "app_to_django:websocket"
    networks:
      - websocket_net

  graph:
    build: ./graph
    container_name: graph
    depends_on:
      - master
    environment:
      - "ROS_HOSTNAME=graph"
      - "ROS_MASTER_URI=http://master:11311"
    volumes:
      - roslogs:/root/.ros/log/
      - ${PWD}/graph:/ws/src/graph   
    restart: always
    #command: python3 manage.py runserver 0.0.0.0:8300
    command: 
      - /bin/bash
      - -c 
      - |        
        python3 manage.py migrate
        python3 manage.py runsslserver 0.0.0.0:8300 --certificate djangossl.cert --key djangossl.key

    ports:
      - 8300:8300
    networks:
      rosnet:
        ipv4_address: 172.18.0.102


volumes:
  roslogs:

networks:
  websocket_net:
    driver: bridge

  rosnet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/24

